version: '2'
services:
    fuelbuddy-app:
        image: fuelbuddy
        external_links:
            - fuelbuddy-mysql:mysql
            - fuelbuddy-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fuelbuddy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    fuelbuddy-mysql:
        extends:
            file: mysql.yml
            service: fuelbuddy-mysql
    fuelbuddy-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: fuelbuddy-elasticsearch
